import { MetadataRoute } from 'next'
import { publishedProducts } from '@/data/portfolio'

// nibango landing (public/nibango, generated by the nibango repo): English at
// /nibango, the other 16 languages under /nibango/<lang>.
const NIBANGO_LANDING_LANGS = ['es', 'ar', 'de', 'fr', 'hi', 'id', 'it', 'ja', 'ko', 'nl', 'pl', 'pt-br', 'ru', 'sv', 'tr', 'zh-hans']

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: 'https://beatlabs.ae',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
    },
    {
      url: 'https://beatlabs.ae/apps',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://beatlabs.ae/studios',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    ...publishedProducts.map(p => ({
      url: `https://beatlabs.ae/apps/${p.slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    })),
    {
      url: 'https://beatlabs.ae/nibango',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    ...NIBANGO_LANDING_LANGS.map(lang => ({
      url: `https://beatlabs.ae/nibango/${lang}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    })),
    {
      url: 'https://beatlabs.ae/legal',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
  ]
}
